spring: 
  profiles: 
    active: 
    - dev 
---
server: 
  port: 8201
spring: 
  profiles: dev
  application: 
    name: smart-config-client

eureka: 
  client: 
    service-url: 
      defaultZone: http://weisuoyun1.com:8001/eureka/
---
server: 
  port: 8202
spring: 
  profiles: test
  application: 
    name: smart-config-client

eureka: 
  client: 
    service-url: 
      defaultZone: http://weisuoyun1.com:8001/eureka/